### ISSUE TITLE
`account` is not defined

### ISSUE THREAD

**Issue by jameshfisher** [stripe-samples/connect-onboarding-for-standard#131]
Is this supposed to be `accountID` rather than `account.id`? Because `accountID` is currently not used.

https://github.com/stripe-samples/connect-onboarding-for-standard/blob/66032aba27d7b792f84b46b18657a68f85b99829/server/node/server.js#L71

**Comment by cjavilla-stripe** [comment]
ack. I think this is fixed with this PR: https://github.com/stripe-samples/connect-onboarding-for-standard/pull/103 thanks!
