### ISSUE TITLE
What to do in case of getting "account with this email already exist" on account creation

### ISSUE THREAD

**Issue by cayasso** [stripe-samples/connect-onboarding-for-standard#2]
While testing I ran into this issue. If an account already exists for a given email, I can't create a new one. Stripe throws the error `account with this email already exist`.

In this particular case and based on this new onboarding flow what is your recommended way to get the accountId and finally create the account link. How do I connect to that existing account? In this case do I need to go back to old OAuth flow? :-(

**Comment by thorsten-stripe** [comment]
@cayasso very sorry for the delay, not all repos are actively monitored for questions. For integration questions, please use our technical IRC chat: https://webchat.freenode.net/#stripe
